# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    
  build:
  
    defaults:
      run:
        working-directory: application/${{ matrix.project }}

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        project: [frontend, api, db-seed]        

    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push azure        
        uses: azure/docker-login@v1
        with:
          username: chipmunks123
          password: d9WLDH23kCplW+JwasvJTCIHxGbDabsB          
          login-server: chipmunks123.azurecr.io
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chipmunks123.azurecr.io/${{ matrix.project }}:${{ github.sha }}
          context: ./application/${{ matrix.project }}
          file: application/${{ matrix.project }}/Dockerfile
